# Input: SQLite 表结构对应的 dataclass 模型。
# Output: 输出项目、会话、JD、轨迹和产物实体类型。
# Pos: 数据库实体定义文件。
# Rule: 一旦我被更新，务必同步更新本文件头注释与所属目录 README。
"""Database entity models for M1 persistence."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Optional


@dataclass
class Project:
    """Project model."""

    id: str
    name: str
    cycle: Optional[str] = None
    base_resume_path: Optional[str] = None
    created_at: Optional[datetime] = None


@dataclass
class ProjectJDEntry:
    """Project JD entry model."""

    id: str
    project_id: str
    raw_content: str
    source_file: Optional[str] = None
    created_at: Optional[datetime] = None


@dataclass
class AgentSession:
    """One chat session bound to one project."""

    id: str
    project_id: str
    title: str
    status: str = "active"
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


@dataclass
class SessionMessage:
    """One persisted session message."""

    id: str
    session_id: str
    role: str
    content: str
    metadata_json: str = "{}"
    created_at: Optional[datetime] = None


@dataclass
class CandidateProfile:
    """Structured candidate profile snapshot for one project."""

    project_id: str
    summary: str = ""
    basics_json: str = "{}"
    preferences_json: str = "{}"
    constraints_json: str = "{}"
    updated_at: Optional[datetime] = None


@dataclass
class ExperienceItem:
    """Structured reusable experience item."""

    id: str
    project_id: str
    title: str
    organization: str = ""
    time_range: str = ""
    summary: str = ""
    tags_json: str = "[]"
    metrics_json: str = "[]"
    evidence_json: str = "[]"
    confidence: float = 0.7
    source: str = "dialog"
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


@dataclass
class JobTrack:
    """One long-lived job track under one project."""

    id: str
    project_id: str
    name: str
    positioning: str = ""
    core_keywords_json: str = "[]"
    resume_strategy: str = ""
    default_resume_outline: str = ""
    primary_jd_entry_id: str = ""
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


@dataclass
class JobTrackJDLink:
    """Link one project-owned JD to one job track."""

    id: str
    track_id: str
    project_jd_entry_id: str
    metadata_json: str = "{}"
    created_at: Optional[datetime] = None


@dataclass
class RunTrace:
    """Persisted think-call-observe trace."""

    id: str
    project_id: str
    session_id: str
    message_id: str
    step_index: int
    kind: str
    payload_json: str = "{}"
    created_at: Optional[datetime] = None


@dataclass
class AgentArtifact:
    """Artifact metadata generated by the new runtime."""

    id: str
    project_id: str
    track_id: str
    jd_entry_id: str = ""
    artifact_type: str = ""
    version: int = 1
    path: str = ""
    summary_json: str = "{}"
    created_at: Optional[datetime] = None
